### ISSUE TITLE
Logo is not displayed correctly

### ISSUE THREAD

**Issue by Dev-Tera** [Frosch2010/discord-color-cards#1]
The logo is not displayed correctly in the Windows command prompt.
![issue](https://user-images.githubusercontent.com/60036493/113478875-da5fab80-948b-11eb-8e3a-de5fab246d5c.png)

**Comment by jens-muenker** [comment]
Thank you for reporting.
The bug should be fixed in the new version 1.0.1. However, the Python package colorama is now additionally required for this version.
